url: "https://wilsoncolin.github.io"
baseurl: "" # the subpath of your site, e.g. /blog
title: "Wilson Colin Design"

# Include icons in the footer for each username enter
footer-links:
        github: WilsonColin
        linkedin: techwilsoncolin
